# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 10:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insta_mini', '0004_auto_20170730_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='username',
            field=models.CharField(max_length=120),
        ),
    ]
